# air.toml

[build]
	cmd = "go build -o tmp/main.exe main.go"
	bin = "tmp/main.exe"
	full_bin = ""
	exclude_dir = ["vendor"]
	include_ext = ["go", "jet"]         # Tell air to watch .go and .jet files
	follow_symlink = false
	delay = 1000                        # milliseconds
	stop_on_error = true
[run]
	cmd = "tmp/main.exe"
[log]
	time = true

[color]
	main = "yellow"
	watcher = "cyan"
	build = "green"
	runner = "magenta"

[debug]
	enable = false
	# You can optionally enable these if you're debugging air behavior
	# log = "air.log"

[watch]
	# Watch Go files in the current directory recursively
	path = "."
	extensions = ["go", "jet"]          # Jet templates
	exclude_dir = ["vendor", "tmp"]
	include = ["view/**"]